CREATE DATABASE IF NOT EXISTS coolbank;

CREATE TABLE IF NOT EXISTS account(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (100),
balance FLOAT);

START TRANSACTION;
SELECT  balance FROM account WHERE id=1;
UPDATE account SET balance = balance + 100 WHERE id = 1;
COMMIT;